In [ ]:
# 

In [4]:
import numpy as np

In [5]:
#Creating array
arr = np.arange(0,11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
#Numpy indexing and selection

In [8]:
arr[8] 

8

In [9]:
arr[1:5]  # Values in range using index

array([1, 2, 3, 4])

In [10]:
#Broadcasting data to array

In [11]:
arr[0:5]=100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
#Slices of array

In [17]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [18]:
#changing slice data
slice_of_arr[:]=99
slice_of_arr  

array([99, 99, 99, 99, 99, 99])

In [21]:
#Data is not copied, it's a view of the original array! This avoids memory problems
arr   # changes in slice causes change in original array


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
#To create copy of array
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
# Numpy 2D array
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
#Indexing row ( indexing starts from the 0)
arr_2d[0]


array([ 5, 10, 15])

In [32]:
arr_2d[1]

array([20, 25, 30])

In [33]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [34]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [36]:
#Set up matrix
arr2d = np.zeros((10,10))   # create an array of 10*10
arr_length = arr2d.shape[1] # get the lenght of array to print the elmetns
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [38]:
arr2d[[2,4,6,8]]  # printing specific rows

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [39]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

In [40]:
# Array elemtsn comparison

In [41]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [45]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [46]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [47]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
# Numpy arithmetic operations

In [51]:
import numpy as np
arr = np.arange(0,10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr + arr   # array elemts summation

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [53]:
arr * arr   # multi

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [54]:
arr - arr   # subtraction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [55]:
arr/arr   # division  
# notice the error for 0/0 as it is invalid division scenario

C:\Users\Sandman\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [56]:
1/arr   # 1/0 infinity

C:\Users\Sandman\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111])

In [57]:
arr**3  # power function using numpy

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [58]:
np.sqrt(arr)  # square root

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [59]:
# exponential (e^)
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [60]:
np.max(arr) #Max element

9

In [62]:
np.min(arr) #Min element

0

In [63]:
# Numpy array

In [64]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [65]:
np.array(my_list)

array([1, 2, 3])

In [66]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [67]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
np.arange(0,10)  # array using range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np.arange(0,11,2)  # array with sepcific interval

array([ 0,  2,  4,  6,  8, 10])

In [71]:
np.zeros(3) # array with 0 elements values

array([ 0.,  0.,  0.])

In [72]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [73]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [74]:
np.linspace(0,10,3)  # gives evenly spaced array 

array([  0.,   5.,  10.])

In [75]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

In [76]:
np.eye(4)  # identity matrix

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [77]:
np.random.rand(2)   # creating random values 

array([ 0.40036347,  0.61963765])

In [78]:
np.random.rand(5,5)

array([[ 0.39567037,  0.99639902,  0.40831456,  0.63707731,  0.89666526],
       [ 0.91567816,  0.5870505 ,  0.97633217,  0.16328924,  0.25592933],
       [ 0.56763995,  0.47709954,  0.37584528,  0.04859531,  0.56808268],
       [ 0.85075774,  0.58928827,  0.93398545,  0.38793242,  0.60211264],
       [ 0.80456101,  0.62330656,  0.40923419,  0.4296398 ,  0.70193375]])

In [80]:
np.random.randint(1,100) # returns random value between range low (inclusive) to high (exclusive)

97

In [84]:
# Vector
arr = np.arange(25)
arr.shape


(25,)

In [85]:
arr.reshape(1,25) # reshaping the array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [86]:
arr.reshape(1,25).shape  # 

(1, 25)

In [87]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [88]:
arr.dtype  # to check the data type of array elemnts

dtype('int32')

In [89]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [90]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [91]:
mat.sum()  # get the summation of all the elements in the array

325

In [92]:
mat.std()  # Standard deviaton

7.2111025509279782

In [93]:
mat.sum(axis=0)  # Colums wise sum

array([55, 60, 65, 70, 75])

In [96]:
# Python scipy
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,8]])


In [99]:
from scipy import linalg   # linear algebra using scipy
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [100]:
linalg.det(A)   # Computing the determinant of the matrix

2.999999999999997

Compute pivoted LU decomposition of a matrix.
The decomposition is::
A = P L U
where P is a permutation matrix, L lower triangular with unit diagonal elements, and U upper triangular.

In [101]:
P, L, U = linalg.lu(A)

In [102]:
P

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]])

In [103]:
L

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.14285714,  1.        ,  0.        ],
       [ 0.57142857,  0.5       ,  1.        ]])

In [104]:
U

array([[ 7.        ,  8.        ,  8.        ],
       [ 0.        ,  0.85714286,  1.85714286],
       [ 0.        ,  0.        ,  0.5       ]])

In [105]:
np.dot(L,U)

array([[ 7.,  8.,  8.],
       [ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [106]:
EW, EV = linalg.eig(A)  # to fing the eigen values and eigen vectors

In [107]:
EW

array([ 15.55528261+0.j,  -1.41940876+0.j,  -0.13587385+0.j])

In [108]:
EV

array([[-0.24043423, -0.67468642,  0.51853459],
       [-0.54694322, -0.23391616, -0.78895962],
       [-0.80190056,  0.70005819,  0.32964312]])

In [109]:
v = np.array([[2],[3],[5]])

In [110]:
v

array([[2],
       [3],
       [5]])

In [111]:
s = linalg.solve(A,v)   # solving system of linear algebra

In [112]:
s

array([[-2.33333333],
       [ 3.66666667],
       [-1.        ]])

In [113]:
from scipy import sparse  # Sparse linear algebra

In [114]:
A = sparse.lil_matrix((1000, 1000))
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in LInked List format>

In [115]:
A[0,:100] = np.random.rand(100)

In [116]:
A[1,100:200] = A[0,:100]

In [117]:
A.setdiag(np.random.rand(1000))

In [118]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in LInked List format>

In [119]:
from scipy.sparse import linalg

In [120]:
# Convert this matrix to Compressed Sparse Row format.
A.tocsr()

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in Compressed Sparse Row format>

In [121]:
A = A.tocsr()

In [122]:
b = np.random.rand(1000)

In [123]:
linalg.spsolve(A, b)

array([ -5.54109968e+02,  -1.09646493e+02,   3.98516466e-01,
         3.54941509e-01,   1.01035413e+00,   1.15168929e+00,
         5.79057995e-02,   3.21034272e-01,   1.54434441e+00,
         4.97113513e+00,   1.23816212e+00,   4.66808932e+00,
         9.66079092e-02,   1.12657122e+00,   6.47888150e-01,
         6.83397219e-01,   1.82464371e+00,   1.05153204e+00,
         2.02518940e+00,   1.55606493e+00,   2.31979713e-01,
         1.05518284e+00,   1.05839127e+00,   3.43299680e-01,
         3.29451464e+00,   8.71175120e-02,   3.02134864e+00,
         9.59342622e-01,   2.59072748e-01,   1.74425302e+00,
         1.80243056e+00,   1.34833286e+01,   8.56209024e-01,
         6.59056395e-01,   5.70703992e-01,   1.03272822e+00,
         5.39945376e+00,   1.48392098e+01,   4.17936469e-01,
         7.35702511e-01,   1.43786225e+00,   2.73339637e+00,
         1.51225854e+00,   5.90956954e-01,   4.70310016e-01,
         9.84468504e+00,   9.00133690e-01,   8.87926533e-01,
         8.78341111e-01,

Linear algebra operations using scipy.linalg

In [1]:
from scipy import linalg

In [7]:
arr = np.array([[1, 2],
                [3, 4]])

In [8]:
linalg.det(arr)   # determinant of square matrix

-2.0

In [9]:
iarr = linalg.inv(arr) # inverse of square matrix

In [10]:
iarr

array([[-2. ,  1. ],
       [ 1.5, -0.5]])